### ISSUE TITLE
License

### ISSUE THREAD

**Issue by hturner** [forwards/forwards.github.io#2]
The repository is marked as CC0 but this is not stated on the website. I think we should change this to CC-BY as we plan to add more content that it is reasonable to expect attribution for e.g. survey reports/blog posts, our own gender summaries, etc. Would that be okay?

**Comment by dicook** [comment]
Yes, this is ok %^)

> On Oct 16, 2016, at 6:22 AM, hturner notifications@github.com wrote:
> 
> The repository is marked as CC0 but this is not stated on the website. I think we should change this to CC-BY as we plan to add more content that it is reasonable to expect attribution for e.g. survey reports/blog posts, our own gender summaries, etc. Would that be okay?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

---

Di Cook
visnut@gmail.com

**Comment by hturner** [comment]
Fixed in 7d0f5d91bb97f00006ca763b5550fc6655d458a8
