### ISSUE TITLE
Typo in about

### ISSUE THREAD

**Issue by d4tagirl** [forwards/forwards.github.io#4]
Hi! Sorry to open an issue about this, but I didn't want to build the whole site just to correct a typo.

It says:
"... in December 2015 to address the underrepresentation of women and rebranded in **Janurary** 2017..."

Please tell me if there is a better way to address this :)

**Comment by hturner** [comment]
Thanks for the report @d4tagirl it should be fixed now. If you notice any issues with the website in future, please add an issue to forwards/website_source as this is the repository that holds the source code for our website, forwards/forward.github.io is the publication repo.

**Comment by d4tagirl** [comment]
Will do, sorry about that! I haven't noticed it was just an .md file and I thought I would have to build the whole site just to fix this. Thanks you!
